os: linux

arch:
  - amd64
  - ppc64le
  
language: closure

jobs:
  include:
    - distro: bionic
      arch: amd64
    - distro: focal
      arch: amd64
    - distro: bionic
      arch: ppc64le
    - distro: focal
      arch: ppc64le
