os: linux
language: go
  
jobs:
  include:
    - &test
      script: go version
      dist: xenial
      arch: amd64
      go: 1.14
    - <<:  *test
      dist: bionic
      arch: ppc64le
      go: 1.15
