os: linux
language: go

go:
  - 1.14
  - 1.15
  - 1.16
  
dist:
  - xenial
  - bionic
  - focal
  
jobs:
  include:
    - &test
      script: go version
      arch: amd64
    - <<:  *test
      arch: ppc64le
